build/ffmpeg-$(FFMPEG_VERSION)/build-base-audio/ffbuild/config.mak: build/inst/base/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-audio/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-audio/ffbuild/config.mak: build/inst/base/lib/pkgconfig/vorbis.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-audio/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/vorbis.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-audio/ffbuild/config.mak: build/inst/base/lib/libmp3lame.a
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-audio/ffbuild/config.mak: build/inst/thr/lib/libmp3lame.a
build/ffmpeg-$(FFMPEG_VERSION)/build-base-audio/ffbuild/config.mak: build/inst/base/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-audio/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/opus.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-base-audio/ffbuild/config.mak: build/inst/base/lib/pkgconfig/vorbis.pc
build/ffmpeg-$(FFMPEG_VERSION)/build-thr-audio/ffbuild/config.mak: build/inst/thr/lib/pkgconfig/vorbis.pc
