name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run tests and typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install libav-audio-decode dependencies
        working-directory: src/libav-audio-decode
        run: npm install
      - name: Install libavneiro dependencies
        working-directory: src/neiro-libav
        run: npm install
      - name: Typecheck
        working-directory: src/neiro-libav
        run: npm run typecheck
      - name: Build
        working-directory: src/neiro-libav
        run: npm run build
      - name: Run Tests
        working-directory: src/libavneiro
        run: npm run test
